import type { Surah, Anime, RadioStation, LiveTvChannel } from './types';

export const initialQuranData: Surah[] = [
    { number: 1, name: "الفاتحة", englishName: "Al-Fatiha", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/001.mp3" },
    { number: 2, name: "البقرة", englishName: "Al-Baqarah", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/002.mp3" },
    { number: 3, name: "آل عمران", englishName: "Aal-E-Imran", englishNameTranslation: "The Family of Imran", numberOfAyahs: 200, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/003.mp3" },
    { number: 4, name: "النساء", englishName: "An-Nisa", englishNameTranslation: "The Women", numberOfAyahs: 176, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/004.mp3" },
    { number: 5, name: "المائدة", englishName: "Al-Ma'idah", englishNameTranslation: "The Table Spread", numberOfAyahs: 120, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/005.mp3" },
    { number: 6, name: "الأنعام", englishName: "Al-An'am", englishNameTranslation: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/006.mp3" },
    { number: 7, name: "الأعراف", englishName: "Al-A'raf", englishNameTranslation: "The Heights", numberOfAyahs: 206, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/007.mp3" },
    { number: 8, name: "الأنفال", englishName: "Al-Anfal", englishNameTranslation: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/008.mp3" },
    { number: 9, name: "التوبة", englishName: "At-Tawbah", englishNameTranslation: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/009.mp3" },
    { number: 10, name: "يونس", englishName: "Yunus", englishNameTranslation: "Jonah", numberOfAyahs: 109, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/010.mp3" },
    { number: 11, name: "هود", englishName: "Hud", englishNameTranslation: "Hud", numberOfAyahs: 123, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/011.mp3" },
    { number: 12, name: "يوسف", englishName: "Yusuf", englishNameTranslation: "Joseph", numberOfAyahs: 111, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/012.mp3" },
    { number: 13, name: "الرعد", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", numberOfAyahs: 43, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/013.mp3" },
    { number: 14, name: "ابراهيم", englishName: "Ibrahim", englishNameTranslation: "Abraham", numberOfAyahs: 52, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/014.mp3" },
    { number: 15, name: "الحجر", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/015.mp3" },
    { number: 16, name: "النحل", englishName: "An-Nahl", englishNameTranslation: "The Bee", numberOfAyahs: 128, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/016.mp3" },
    { number: 17, name: "الإسراء", englishName: "Al-Isra", englishNameTranslation: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/017.mp3" },
    { number: 18, name: "الكهف", englishName: "Al-Kahf", englishNameTranslation: "The Cave", numberOfAyahs: 110, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/018.mp3" },
    { number: 19, name: "مريم", englishName: "Maryam", englishNameTranslation: "Mary", numberOfAyahs: 98, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/019.mp3" },
    { number: 20, name: "طه", englishName: "Taha", englishNameTranslation: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/020.mp3" },
    { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", englishNameTranslation: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/021.mp3" },
    { number: 22, name: "الحج", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/022.mp3" },
    { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", englishNameTranslation: "The Believers", numberOfAyahs: 118, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/023.mp3" },
    { number: 24, name: "النور", englishName: "An-Nur", englishNameTranslation: "The Light", numberOfAyahs: 64, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/024.mp3" },
    { number: 25, name: "الفرقان", englishName: "Al-Furqan", englishNameTranslation: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/025.mp3" },
    { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", englishNameTranslation: "The Poets", numberOfAyahs: 227, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/026.mp3" },
    { number: 27, name: "النمل", englishName: "An-Naml", englishNameTranslation: "The Ant", numberOfAyahs: 93, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/027.mp3" },
    { number: 28, name: "القصص", englishName: "Al-Qasas", englishNameTranslation: "The Stories", numberOfAyahs: 88, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/028.mp3" },
    { number: 29, name: "العنكبوت", englishName: "Al-Ankabut", englishNameTranslation: "The Spider", numberOfAyahs: 69, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/029.mp3" },
    { number: 30, name: "الروم", englishName: "Ar-Rum", englishNameTranslation: "The Romans", numberOfAyahs: 60, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/030.mp3" },
    { number: 31, name: "لقمان", englishName: "Luqman", englishNameTranslation: "Luqman", numberOfAyahs: 34, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/031.mp3" },
    { number: 32, name: "السجدة", englishName: "As-Sajdah", englishNameTranslation: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/032.mp3" },
    { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", englishNameTranslation: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/033.mp3" },
    { number: 34, name: "سبإ", englishName: "Saba", englishNameTranslation: "Sheba", numberOfAyahs: 54, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/034.mp3" },
    { number: 35, name: "فاطر", englishName: "Fatir", englishNameTranslation: "Originator", numberOfAyahs: 45, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/035.mp3" },
    { number: 36, name: "يس", englishName: "Ya-Sin", englishNameTranslation: "Ya Sin", numberOfAyahs: 83, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/036.mp3" },
    { number: 37, name: "الصافات", englishName: "As-Saffat", englishNameTranslation: "Those who set the Ranks", numberOfAyahs: 182, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/037.mp3" },
    { number: 38, name: "ص", englishName: "Sad", englishNameTranslation: "The Letter 'Sad'", numberOfAyahs: 88, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/038.mp3" },
    { number: 39, name: "الزمر", englishName: "Az-Zumar", englishNameTranslation: "The Troops", numberOfAyahs: 75, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/039.mp3" },
    { number: 40, name: "غافر", englishName: "Ghafir", englishNameTranslation: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/040.mp3" },
    { number: 41, name: "فصلت", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", numberOfAyahs: 54, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/041.mp3" },
    { number: 42, name: "الشورى", englishName: "Ash-Shuraa", englishNameTranslation: "The Consultation", numberOfAyahs: 53, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/042.mp3" },
    { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", englishNameTranslation: "The Ornaments of Gold", numberOfAyahs: 89, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/043.mp3" },
    { number: 44, name: "الدخان", englishName: "Ad-Dukhan", englishNameTranslation: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/044.mp3" },
    { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", englishNameTranslation: "The Crouching", numberOfAyahs: 37, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/045.mp3" },
    { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", englishNameTranslation: "The Wind-Curved Sandhills", numberOfAyahs: 35, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/046.mp3" },
    { number: 47, name: "محمد", englishName: "Muhammad", englishNameTranslation: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/047.mp3" },
    { number: 48, name: "الفتح", englishName: "Al-Fath", englishNameTranslation: "The Victory", numberOfAyahs: 29, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/048.mp3" },
    { number: 49, name: "الحجرات", englishName: "Al-Hujurat", englishNameTranslation: "The Rooms", numberOfAyahs: 18, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/049.mp3" },
    { number: 50, name: "ق", englishName: "Qaf", englishNameTranslation: "The Letter 'Qaf'", numberOfAyahs: 45, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/050.mp3" },
    { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", englishNameTranslation: "The Winnowing Winds", numberOfAyahs: 60, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/051.mp3" },
    { number: 52, name: "الطور", englishName: "At-Tur", englishNameTranslation: "The Mount", numberOfAyahs: 49, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/052.mp3" },
    { number: 53, name: "النجم", englishName: "An-Najm", englishNameTranslation: "The Star", numberOfAyahs: 62, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/053.mp3" },
    { number: 54, name: "القمر", englishName: "Al-Qamar", englishNameTranslation: "The Moon", numberOfAyahs: 55, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/054.mp3" },
    { number: 55, name: "الرحمن", englishName: "Ar-Rahman", englishNameTranslation: "The Beneficent", numberOfAyahs: 78, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/055.mp3" },
    { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", englishNameTranslation: "The Inevitable", numberOfAyahs: 96, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/056.mp3" },
    { number: 57, name: "الحديد", englishName: "Al-Hadid", englishNameTranslation: "The Iron", numberOfAyahs: 29, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/057.mp3" },
    { number: 58, name: "المجادلة", englishName: "Al-Mujadila", englishNameTranslation: "The Pleading Woman", numberOfAyahs: 22, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/058.mp3" },
    { number: 59, name: "الحشر", englishName: "Al-Hashr", englishNameTranslation: "The Exile", numberOfAyahs: 24, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/059.mp3" },
    { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", englishNameTranslation: "She that is to be examined", numberOfAyahs: 13, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/060.mp3" },
    { number: 61, name: "الصف", englishName: "As-Saf", englishNameTranslation: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/061.mp3" },
    { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", englishNameTranslation: "The Congregation, Friday", numberOfAyahs: 11, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/062.mp3" },
    { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", englishNameTranslation: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/063.mp3" },
    { number: 64, name: "التغابن", englishName: "At-Taghabun", englishNameTranslation: "The Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/064.mp3" },
    { number: 65, name: "الطلاق", englishName: "At-Talaq", englishNameTranslation: "The Divorce", numberOfAyahs: 12, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/065.mp3" },
    { number: 66, name: "التحريم", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", numberOfAyahs: 12, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/066.mp3" },
    { number: 67, name: "الملك", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/067.mp3" },
    { number: 68, name: "القلم", englishName: "Al-Qalam", englishNameTranslation: "The Pen", numberOfAyahs: 52, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/068.mp3" },
    { number: 69, name: "الحاقة", englishName: "Al-Haqqah", englishNameTranslation: "The Reality", numberOfAyahs: 52, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/069.mp3" },
    { number: 70, name: "المعارج", englishName: "Al-Ma'arij", englishNameTranslation: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/070.mp3" },
    { number: 71, name: "نوح", englishName: "Nuh", englishNameTranslation: "Noah", numberOfAyahs: 28, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/071.mp3" },
    { number: 72, name: "الجن", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/072.mp3" },
    { number: 73, name: "المزمل", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/073.mp3" },
    { number: 74, name: "المدثر", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/074.mp3" },
    { number: 75, name: "القيامة", englishName: "Al-Qiyamah", englishNameTranslation: "The Resurrection", numberOfAyahs: 40, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/075.mp3" },
    { number: 76, name: "الانسان", englishName: "Al-Insan", englishNameTranslation: "Man", numberOfAyahs: 31, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/076.mp3" },
    { number: 77, name: "المرسلات", englishName: "Al-Mursalat", englishNameTranslation: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/077.mp3" },
    { number: 78, name: "النبإ", englishName: "An-Naba", englishNameTranslation: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/078.mp3" },
    { number: 79, name: "النازعات", englishName: "An-Nazi'at", englishNameTranslation: "Those who drag forth", numberOfAyahs: 46, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/079.mp3" },
    { number: 80, name: "عبس", englishName: "Abasa", englishNameTranslation: "He Frowned", numberOfAyahs: 42, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/080.mp3" },
    { number: 81, name: "التكوير", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/081.mp3" },
    { number: 82, name: "الإنفطار", englishName: "Al-Infitar", englishNameTranslation: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/082.mp3" },
    { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", englishNameTranslation: "The Defrauding", numberOfAyahs: 36, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/083.mp3" },
    { number: 84, name: "الإنشقاق", englishName: "Al-Inshiqaq", englishNameTranslation: "The Sundering", numberOfAyahs: 25, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/084.mp3" },
    { number: 85, name: "البروج", englishName: "Al-Buruj", englishNameTranslation: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/085.mp3" },
    { number: 86, name: "الطارق", englishName: "At-Tariq", englishNameTranslation: "The Nightcommer", numberOfAyahs: 17, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/086.mp3" },
    { number: 87, name: "الأعلى", englishName: "Al-A'la", englishNameTranslation: "The Most High", numberOfAyahs: 19, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/087.mp3" },
    { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", englishNameTranslation: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/088.mp3" },
    { number: 89, name: "الفجر", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/089.mp3" },
    { number: 90, name: "البلد", englishName: "Al-Balad", englishNameTranslation: "The City", numberOfAyahs: 20, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/090.mp3" },
    { number: 91, name: "الشمس", englishName: "Ash-Shams", englishNameTranslation: "The Sun", numberOfAyahs: 15, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/091.mp3" },
    { number: 92, name: "الليل", englishName: "Al-Layl", englishNameTranslation: "The Night", numberOfAyahs: 21, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/092.mp3" },
    { number: 93, name: "الضحى", englishName: "Ad-Duhaa", englishNameTranslation: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/093.mp3" },
    { number: 94, name: "الشرح", englishName: "Ash-Sharh", englishNameTranslation: "The Relief", numberOfAyahs: 8, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/094.mp3" },
    { number: 95, name: "التين", englishName: "At-Tin", englishNameTranslation: "The Fig", numberOfAyahs: 8, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/095.mp3" },
    { number: 96, name: "العلق", englishName: "Al-Alaq", englishNameTranslation: "The Clot", numberOfAyahs: 19, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/096.mp3" },
    { number: 97, name: "القدر", englishName: "Al-Qadr", englishNameTranslation: "The Power", numberOfAyahs: 5, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/097.mp3" },
    { number: 98, name: "البينة", englishName: "Al-Bayyinah", englishNameTranslation: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/098.mp3" },
    { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", englishNameTranslation: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/099.mp3" },
    { number: 100, name: "العاديات", englishName: "Al-Adiyat", englishNameTranslation: "The Courser", numberOfAyahs: 11, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/100.mp3" },
    { number: 101, name: "القارعة", englishName: "Al-Qari'ah", englishNameTranslation: "The Calamity", numberOfAyahs: 11, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/101.mp3" },
    { number: 102, name: "التكاثر", englishName: "At-Takathur", englishNameTranslation: "The Rivalry in world increase", numberOfAyahs: 8, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/102.mp3" },
    { number: 103, name: "العصر", englishName: "Al-Asr", englishNameTranslation: "The Declining Day", numberOfAyahs: 3, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/103.mp3" },
    { number: 104, name: "الهمزة", englishName: "Al-Humazah", englishNameTranslation: "The Slanderer", numberOfAyahs: 9, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/104.mp3" },
    { number: 105, name: "الفيل", englishName: "Al-Fil", englishNameTranslation: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/105.mp3" },
    { number: 106, name: "قريش", englishName: "Quraysh", englishNameTranslation: "Quraysh", numberOfAyahs: 4, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/106.mp3" },
    { number: 107, name: "الماعون", englishName: "Al-Ma'un", englishNameTranslation: "The Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/107.mp3" },
    { number: 108, name: "الكوثر", englishName: "Al-Kawthar", englishNameTranslation: "The Abundance", numberOfAyahs: 3, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/108.mp3" },
    { number: 109, name: "الكافرون", englishName: "Al-Kafirun", englishNameTranslation: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/109.mp3" },
    { number: 110, name: "النصر", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", numberOfAyahs: 3, revelationType: "Medinan", audioUrl: "https://server6.mp3quran.net/qtm/110.mp3" },
    { number: 111, name: "المسد", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", numberOfAyahs: 5, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/111.mp3" },
    { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", englishNameTranslation: "The Sincerity", numberOfAyahs: 4, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/112.mp3" },
    { number: 113, name: "الفلق", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/113.mp3" },
    { number: 114, name: "الناس", englishName: "An-Nas", englishNameTranslation: "Mankind", numberOfAyahs: 6, revelationType: "Meccan", audioUrl: "https://server6.mp3quran.net/qtm/114.mp3" }
];


const rawAnimeData = {
  'Food Wars! Shokugeki no Soma': [
    { title: 'Ep 1', stream: 'https://rubyvidhub.com/embed-de9gciik2ihy.html?streamrurucy=true' },
    { title: 'Ep 2', stream: 'https://rubyvidhub.com/embed-63gr84pflws6.html?streamrurucy=true' },
    { title: 'Ep 3', stream: 'https://rubyvidhub.com/embed-jlwhyksev3x3.html?streamrurucy=true' },
    { title: 'Ep 4', stream: 'https://rubyvidhub.com/embed-cdn9436wj5d3.html?streamrurucy=true' },
    { title: 'Ep 5', stream: 'https://rubyvidhub.com/embed-uhbxc2vxokar.html?streamrurucy=true' },
    { title: 'Ep 6', stream: 'https://rubyvidhub.com/embed-pv2v9wmrxrwb.html?streamrurucy=true' },
    { title: 'Ep 7', stream: 'https://rubyvidhub.com/embed-n8hf5d8vy5m2.html?streamrurucy=true' },
    { title: 'Ep 8', stream: 'https://rubyvidhub.com/embed-vfm7ju2k7xlz.html?streamrurucy=true' },
    { title: 'Ep 9', stream: 'https://rubyvidhub.com/embed-dgfc9t8o61vn.html?streamrurucy=true' },
    { title: 'Ep 10', stream: 'https://rubyvidhub.com/embed-rrjgay7n70l7.html?streamrurucy=true' },
    { title: 'Ep 11', stream: 'https://rubyvidhub.com/embed-byiyjih29jcr.html?streamrurucy=true' },
    { title: 'Ep 12', stream: 'https://rubyvidhub.com/embed-nhhr0ooqriv4.html?streamrurucy=true' },
    { title: 'Ep 13', stream: 'https://rubyvidhub.com/embed-07rfndqemxqv.html?streamrurucy=true' },
    { title: 'Ep 14', stream: 'https://rubyvidhub.com/embed-e25mepp965u5.html?streamrurucy=true' },
    { title: 'Ep 15', stream: 'https://rubyvidhub.com/embed-ts4wu8m3hk73.html?streamrurucy=true' },
    { title: 'Ep 16', stream: 'https://rubyvidhub.com/embed-fi1dkt3ovle3.html?streamrurucy=true' },
    { title: 'Ep 17', stream: 'https://rubyvidhub.com/embed-fehdic3m7k3a.html?streamrurucy=true' },
    { title: 'Ep 18', stream: 'https://rubyvidhub.com/embed-fihhatsjxpel.html?streamrurucy=true' },
    { title: 'Ep 19', stream: 'https://rubyvidhub.com/embed-2lzh3ej2f5os.html?streamrurucy=true' },
    { title: 'Ep 20', stream: 'https://rubyvidhub.com/embed-q8n3jsm3fijj.html?streamrurucy=true' }
  ],
  'My Dress-Up Darling Season 1': [
    { title: ' Ep 1', stream: 'https://rubyvidhub.com/embed-4aynzi4d5nmx.html?streamrurucy=true' },
    { title: ' Ep 2', stream: 'https://rubyvidhub.com/embed-si7rgvmdgnr1.html?streamrurucy=true' },
    { title: ' Ep 3', stream: 'https://rubyvidhub.com/embed-q5h88cieel8g.html?streamrurucy=true' },
    { title: ' Ep 4', stream: 'https://rubyvidhub.com/embed-j0d6nof4oxy0.html?streamrurucy=true' },
    { title: ' Ep 5', stream: 'https://rubyvidhub.com/embed-h79x45pzmgbn.html?streamrurucy=true' },
    { title: ' Ep 6', stream: 'https://rubyvidhub.com/embed-c1ujmfp8hpno.html?streamrurucy=true' },
    { title: ' Ep 7', stream: 'https://rubyvidhub.com/embed-n6n30u3dy22u.html?streamrurucy=true' },
    { title: ' Ep 8', stream: 'https://rubyvidhub.com/embed-kk7tqj3tdqt3.html?streamrurucy=true' },
    { title: ' Ep 9', stream: 'https://rubyvidhub.com/embed-b6ze6fgiu41z.html?streamrurucy=true' },
    { title: ' Ep 10', stream: 'https://rubyvidhub.com/embed-5qjjgj3slwt0.html?streamrurucy=true' },
    { title: ' Ep 11', stream: 'https://rubyvidhub.com/embed-p5jwgcz7pjof.html?streamrurucy=true' },
    { title: ' Ep 12', stream: 'https://rubyvidhub.com/embed-ku4ie9hwk2wb.html?streamrurucy=true' },
  ],
  'My Dress-Up Darling Season 2': [
    { title: ' Ep 1', stream: 'https://rubyvidhub.com/embed-zssu721sw5hg.html?streamrurucy=true' },
    { title: ' Ep 2', stream: 'https://rubyvidhub.com/embed-uon0r38926mj.html?streamrurucy=true' },
    { title: ' Ep 3', stream: 'https://rubyvidhub.com/embed-ehf47eylm8jg.html?streamrurucy=true' },
    { title: ' Ep 4', stream: 'https://rubyvidhub.com/embed-k7u8qvqknsy5.html?streamrurucy=true' },
    { title: ' Ep 5', stream: 'https://rubyvidhub.com/embed-ya3u04jxxl8u.html?streamrurucy=true' },
    { title: ' Ep 6', stream: 'https://rubyvidhub.com/embed-lcjv5qhmkshe.html?streamrurucy=true' },
    { title: ' Ep 7', stream: 'https://rubyvidhub.com/embed-ezgyjyw75jj8.html?streamrurucy=true' },
    { title: ' Ep 8', stream: 'https://rubyvidhub.com/embed-l3ispua7v4uv.html?streamrurucy=true' },
    { title: ' Ep 9', stream: 'https://rubyvidhub.com/embed-q72qce3bo7jx.html?streamrurucy=true' },
    { title: ' Ep 10', stream: 'https://rubyvidhub.com/embed-vycnnfwvto9u.html?streamrurucy=true' },
    { title: ' Ep 11', stream: 'https://rubyvidhub.com/embed-v8b3q34ri9qi.html?streamrurucy=true' },
    { title: ' Ep 12', stream: 'https://rubyvidhub.com/embed-v8b3q34ri9qi.html?streamrurucy=true' },
  ],
  'Solo Leveling Season 1': [
    { title: ' Ep 1', stream: 'https://rubyvidhub.com/embed-pagwhpjhkpmj.html?streamrurucy=true' },
    { title: ' Ep 2', stream: 'https://rubyvidhub.com/embed-bllodlp2r72v.html?streamrurucy=true' },
    { title: ' Ep 3', stream: 'https://rubyvidhub.com/embed-y87o3tlpp439.html?streamrurucy=true' },
    { title: ' Ep 4', stream: 'https://rubyvidhub.com/embed-p5ut9m9pjntl.html?streamrurucy=true' },
    { title: ' Ep 5', stream: 'https://rubyvidhub.com/embed-zdg94ijfh5ni.html?streamrurucy=true' },
    { title: ' Ep 6', stream: 'https://rubyvidhub.com/embed-wscvj1jnr0qy.html?streamrurucy=true' },
    { title: ' Ep 7', stream: 'https://rubyvidhub.com/embed-iovkl9rt2qmi.html?streamrurucy=true' },
    { title: ' Ep 8', stream: 'https://rubyvidhub.com/embed-n3q479kxugv1.html?streamrurucy=true' },
    { title: ' Ep 9', stream: 'https://rubyvidhub.com/embed-vgohucipvbs5.html?streamrurucy=true' },
    { title: ' Ep 10', stream: 'https://rubyvidhub.com/embed-x0ya0t3vz0no.html?streamrurucy=true' },
    { title: ' Ep 11', stream: 'https://rubyvidhub.com/embed-0ygacld0vp1n.html?streamrurucy=true' },
    { title: ' Ep 12', stream: 'https://rubyvidhub.com/embed-0pw7qltrkfah.html?streamrurucy=true' },
  ],
  'Solo Leveling Season 2': [
    { title: ' Ep 1', stream: 'https://rubyvidhub.com/embed-cfnt58bbbod0.html?streamrurucy=true' },
    { title: ' Ep 2', stream: 'https://rubyvidhub.com/embed-moqvybh1lgdl.html?streamrurucy=true' },
    { title: ' Ep 3', stream: 'https://rubyvidhub.com/embed-fshtmlz6cg4t.html?streamrurucy=true' },
    { title: ' Ep 4', stream: 'https://rubyvidhub.com/embed-49imbydbhnal.html?streamrurucy=true' },
    { title: ' Ep 5', stream: 'https://rubyvidhub.com/embed-8r1rojhz6jbu.html?streamrurucy=true' },
    { title: ' Ep 6', stream: 'https://rubyvidhub.com/embed-qcjfihu03zc7.html?streamrurucy=true' },
    { title: ' Ep 7', stream: 'https://rubyvidhub.com/embed-cxzlz0hza0ya.html?streamrurucy=true' },
    { title: ' Ep 8', stream: 'https://rubyvidhub.com/embed-2cimx2pkmkae.html?streamrurucy=true' },
    { title: ' Ep 9', stream: 'https://rubyvidhub.com/embed-h4c8di779306.html?streamrurucy=true' },
    { title: ' Ep 10', stream: 'https://rubyvidhub.com/embed-98xb60dke2kk.html?streamrurucy=true' },
    { title: ' Ep 11', stream: 'https://rubyvidhub.com/embed-9h2xo0kg1ghg.html?streamrurucy=true' },
    { title: ' Ep 12', stream: 'https://rubyvidhub.com/embed-iinwy8dh353p.html?streamrurucy=true' },
    { title: ' Ep 13', stream: 'https://rubyvidhub.com/embed-badddylrloui.html?streamrurucy=true' },
  ],
};

const animeImageMap: { [key: string]: string } = {
    'Food Wars! Shokugeki no Soma': 'https://i.ibb.co.com/X9zsLxH/unnamed.jpg',
    'My Dress-Up Darling Season 1': 'https://i.ibb.co/RG2xhHJX/unnamed-1.jpg',
    'My Dress-Up Darling Season 2': 'https://i.ibb.co/RG2xhHJX/unnamed-1.jpg',
    'Solo Leveling Season 1': 'https://i.ibb.co/nqty9RSq/unnamed-3.jpg',
    'Solo Leveling Season 2': 'https://i.ibb.co/nqty9RSq/unnamed-3.jpg',
};

export const initialAnimeData: Omit<Anime, 'id'>[] = Object.entries(rawAnimeData).map(([title, episodes]) => {
  const sanitizedTitle = title.replace(/\s+/g, '-').toLowerCase();
  const imageUrl = animeImageMap[title] || `https://picsum.photos/seed/${sanitizedTitle}/500/700`;
  return {
    title,
    imageUrl: imageUrl,
    synopsis: `A thrilling new series. Follow the adventures in "${title}". More details coming soon!`,
    episodes: episodes.map((ep, epIndex) => {
        const epNumMatch = ep.title.match(/Ep (\d+)/i);
        const epNumber = epNumMatch ? parseInt(epNumMatch[1], 10) : epIndex + 1;
        return {
            number: epNumber,
            title: ep.title.trim(),
            videoUrl: ep.stream,
        }
    }),
  }
});

const stationsByCountry = {
    'Bangladesh': [
        { title: 'Bangladesh Betar', stream: 'https://as1.digitalsynapsebd.com/proxy/bbdktraf/stream' },
        { title: 'Dhaka FM', stream: 'https://stream.zeno.fm/u9mphfk604zuv' },
        { title: 'Rajshahi FM', stream: 'https://stream.zeno.fm/nxfshdayjrdvv' },
        { title: 'Radio Today', stream: 'https://stream.zenolive.com/8wv4d8g4344tv' },
        { title: 'Radio Bushra', stream: 'https://stream.zeno.fm/mzuka1fdxzzuv' },
        { title: 'Radio Foorti', stream: 'https://stream.zeno.fm/cwa3vg8s8druv' },
        { title: 'Radio Goongoon', stream: 'https://audio.streamcast.xyz/radio/8000/radio.mp3' },
        { title: 'Radio Padma FM', stream: 'https://radio.garden/api/ara/content/listen/rZztipXo/channel.mp3?1759833209757' },
        { title: 'Radio Mahananda FM', stream: 'https://streaming.radiomahananda.fm/proxy/radiomahananda/stream' }
    ],
    'India': [
        { title: 'Radio Mirchi FM', stream: 'https://eu8.fastcast4u.com/proxy/clyedupq?mp=%2F1?aw_0_req_lsid=2c0fae177108c9a42a7cf24878625444' },
        { title: '92.7 Big FM', stream: 'https://stream.zeno.fm/dbstwo3dvhhtv' },
        { title: 'Radio City FM', stream: 'https://stream.zeno.fm/pxc55r5uyc9uv' },
    ],
    'France': [
        { title: 'France Info', stream: 'http://icecast.radiofrance.fr/franceinfo-midfi.mp3' },
        { title: 'France Inter', stream: 'http://icecast.radiofrance.fr/franceinter-midfi.mp3' },
        { title: 'France Culture', stream: 'http://icecast.radiofrance.fr/franceculture-midfi.mp3' },
        { title: 'FIP', stream: 'http://icecast.radiofrance.fr/fip-midfi.mp3' }
    ],
    'United Kingdom': [
        { title: 'BBC World Service', stream: 'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service' }
    ],
    'Belgium': [
        { title: 'Radio 1 Belgium', stream: 'http://icecast.vrtcdn.be/radio1-high.mp3' },
        { title: 'Studio Brussel', stream: 'http://icecast.vrtcdn.be/stubru-high.mp3' },
        { title: 'Klara', stream: 'http://icecast.vrtcdn.be/klara-high.mp3' }
    ],
    'Germany': [
        { title: 'Deutschlandfunk', stream: 'http://st01.dlf.de/dlf/01/128/mp3/stream.mp3' },
        { title: 'WDR 3', stream: 'http://wdr-wdr3-live.icecast.wdr.de/wdr/wdr3/live/mp3/128/stream.mp3' }
    ],
    'Netherlands': [
        { title: 'NPO Radio 1', stream: 'http://icecast.omroep.nl/radio1-bb-mp3' },
        { title: 'NPO 3FM', stream: 'http://icecast.omroep.nl/3fm-bb-mp3' },
        { title: 'Radio 538', stream: 'http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3' }
    ]
};

export const initialRadioData: Omit<RadioStation, 'id'>[] = Object.entries(stationsByCountry).flatMap(([country, stationList]) => 
    stationList.map(station => ({
        name: station.title,
        genre: country,
        tracks: [{
            title: station.title,
            artist: country,
            audioUrl: station.stream,
        }],
    }))
);

export const initialLiveTvData: Omit<LiveTvChannel, 'id'>[] = [
    { name: "Al Jazeera", logoUrl: "https://i.ibb.co/kXw2H6S/al-jazeera.png", streamUrl: "https://www.youtube.com/embed/live_stream?channel=UCNye-wNBqNL5ZzHSJj3l8Bg", category: "News", type: 'embed' },
    { name: "Duronto TV", logoUrl: "https://i.ibb.co/mHq3HJV/duronto-tv.png", streamUrl: "https://tvsen4.aynaott.com/durontotv/tracks-v1a1/mono.ts.m3u8", category: "Kids", type: "hls" },
    { name: "Madani Channel Bangla", logoUrl: "https://i.ibb.co/CBr2Yv7/madani-channel-bangla.png", streamUrl: "https://streaming.madanichannel.tv/static/streaming-playlists/hls/d3e49b76-ac06-4689-a641-9200445b647f/0.m3u8", category: "Spiritual", type: "hls" },
    { name: "Boishakhi TV", logoUrl: "https://i.ibb.co/zZ9y7hG/Boishakhi-TV-Logo-wine.png", streamUrl: "https://boishakhi.sonarbanglatv.com/boishakhi/boishakhitv/index.m3u8", category: "Entertainment", type: "hls" },
    { name: "Channel 24", logoUrl: "https://i.ibb.co/DRVsm5s/yathe-yathe.jpg", streamUrl: "https://www.youtube.com/embed/live_stream?channel=UCPyZZySmm32N_5qlsd1l3Zg", category: "News", type: 'embed' },
    { name: "Rajdhani TV", logoUrl: "https://i.ibb.co/zZ9y7hG/Boishakhi-TV-Logo-wine.png", streamUrl: "https://stream.shariarsuvo.com/hls5/rajdhanicable.m3u8", category: "Entertainment", type: "hls" }
];
